#annoyingly, can't include .dino first, but .edb needs this

# override the defualt setting in root makefile

override TOOLCHAIN = clang

include ../Makefile

include $(LIB_ROOT)/ratchet/Makefile.target
