all:
	/opt/ti/mspgcc/bin/msp430-elf-gcc -c -I /opt/ti/mspgcc/lib/gcc/msp430-elf/4.9.1/include -I /opt/ti/mspgcc/msp430-elf/include -I /opt/ti/mspgcc/include main.c
	/opt/ti/mspgcc/bin/msp430-elf-gcc -mmcu=msp430fr5969 -o test.out main.o

